/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 room.glb --transform
Author: Anex (https://sketchfab.com/anex)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/room-6417cbc1870a4a1691cca06912ae0369
Title: Room
*/

import { useGLTF } from "@react-three/drei"

export function Model(props) {
  const { nodes, materials } = useGLTF("/room-transformed.glb")
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.Material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials["Material.002"]} />
        <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials["Material.003"]} />
        <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.krzeslo_1} />
        <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials.krzeslo_okno} />
        <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials.krzeslo_prawe} />
        <mesh castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials.krzeslo_srodek} />
        <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials.podloga} />
        <mesh castShadow receiveShadow geometry={nodes.Object_11.geometry} material={materials.sciana_okno} />
        <mesh castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials["stolik.001"]} />
        <mesh castShadow receiveShadow geometry={nodes.Object_16.geometry} material={materials["Material.006"]} />
        <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials["Material.004"]} />
        <mesh geometry={nodes.Object_13.geometry}>
          <meshStandardMaterial transparent opacity={0.5} />
        </mesh>
        <mesh castShadow receiveShadow geometry={nodes.Object_14.geometry} material={materials["Material.002"]} />
        <mesh castShadow receiveShadow geometry={nodes.Object_15.geometry} material={materials["Material.005"]} />
        <mesh castShadow receiveShadow geometry={nodes.Object_17.geometry} material={materials.mata} />
        <mesh castShadow receiveShadow geometry={nodes.Object_18.geometry} material={materials.stolik} />
      </group>
    </group>
  )
}

useGLTF.preload("/room-transformed.glb")
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: FUD-UJEP (https://sketchfab.com/FUD-UJEP)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/la-night-city-a85450184c6e4ddf87b49c402641e5b4
title: LA Night City
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Dtla_Orbit_Dtla_Orbit_u2_v2_0: THREE.Mesh;
    Dtla_Orbit_Dtla_Orbit_u2_v2_0_1: THREE.Mesh;
    Dtla_Orbit_Dtla_Orbit_u2_v2_0_2: THREE.Mesh;
    Dtla_Orbit_Dtla_Orbit_u2_v2_0_3: THREE.Mesh;
    Dtla_Orbit_Dtla_Orbit_u1_v1_0: THREE.Mesh;
    Dtla_Orbit_Dtla_Orbit_u1_v1_0_1: THREE.Mesh;
    Dtla_Orbit_Dtla_Orbit_u1_v1_0_2: THREE.Mesh;
    Dtla_Orbit_Dtla_Orbit_u3_v1_0: THREE.Mesh;
    Dtla_Orbit_Dtla_Orbit_u3_v1_0_1: THREE.Mesh;
    Dtla_Orbit_Dtla_Orbit_u3_v1_0_2: THREE.Mesh;
    Dtla_Orbit_Dtla_Orbit_u3_v1_0_3: THREE.Mesh;
    Dtla_Orbit_Dtla_Orbit_u2_v1_0: THREE.Mesh;
    Dtla_Orbit_Dtla_Orbit_u2_v1_0_1: THREE.Mesh;
    Dtla_Orbit_Dtla_Orbit_u2_v1_0_2: THREE.Mesh;
    Dtla_Orbit_Dtla_Orbit_u2_v1_0_3: THREE.Mesh;
    Dtla_Orbit_Dtla_Orbit_u1_v2_0: THREE.Mesh;
    Dtla_Orbit_Dtla_Orbit_u1_v2_0_1: THREE.Mesh;
    Dtla_Orbit_Dtla_Orbit_u1_v2_0_2: THREE.Mesh;
    Dtla_Orbit_Dtla_Orbit_u1_v2_0_3: THREE.Mesh;
  };
  materials: {
    Dtla_Orbit_u2_v2: THREE.MeshBasicMaterial;
    Dtla_Orbit_u1_v1: THREE.MeshBasicMaterial;
    Dtla_Orbit_u3_v1: THREE.MeshBasicMaterial;
    Dtla_Orbit_u2_v1: THREE.MeshBasicMaterial;
    Dtla_Orbit_u1_v2: THREE.MeshBasicMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/la_night_city.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.12}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v2_0.geometry}
              material={materials.Dtla_Orbit_u2_v2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v2_0_1.geometry}
              material={materials.Dtla_Orbit_u2_v2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v2_0_2.geometry}
              material={materials.Dtla_Orbit_u2_v2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v2_0_3.geometry}
              material={materials.Dtla_Orbit_u2_v2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v1_0.geometry}
              material={materials.Dtla_Orbit_u1_v1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v1_0_1.geometry}
              material={materials.Dtla_Orbit_u1_v1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v1_0_2.geometry}
              material={materials.Dtla_Orbit_u1_v1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u3_v1_0.geometry}
              material={materials.Dtla_Orbit_u3_v1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u3_v1_0_1.geometry}
              material={materials.Dtla_Orbit_u3_v1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u3_v1_0_2.geometry}
              material={materials.Dtla_Orbit_u3_v1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u3_v1_0_3.geometry}
              material={materials.Dtla_Orbit_u3_v1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v1_0.geometry}
              material={materials.Dtla_Orbit_u2_v1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v1_0_1.geometry}
              material={materials.Dtla_Orbit_u2_v1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v1_0_2.geometry}
              material={materials.Dtla_Orbit_u2_v1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v1_0_3.geometry}
              material={materials.Dtla_Orbit_u2_v1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v2_0.geometry}
              material={materials.Dtla_Orbit_u1_v2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v2_0_1.geometry}
              material={materials.Dtla_Orbit_u1_v2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v2_0_2.geometry}
              material={materials.Dtla_Orbit_u1_v2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v2_0_3.geometry}
              material={materials.Dtla_Orbit_u1_v2}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/la_night_city.glb");